import { describe, it, expect, vi, beforeEach } from "vitest";

// Set Redsys env vars before importing the module
vi.stubEnv("REDSYS_MERCHANT_CODE", "999008881");
vi.stubEnv("REDSYS_MERCHANT_KEY", "sq7HjrUOBfKmC576ILgskD5srU870gJ7");
vi.stubEnv("REDSYS_MERCHANT_TERMINAL", "001");
vi.stubEnv("REDSYS_ENVIRONMENT", "test");

vi.mock("@/lib/logger", () => ({
  logger: {
    child: () => ({
      info: vi.fn(),
      error: vi.fn(),
      warn: vi.fn(),
    }),
  },
}));

import {
  buildRedsysForm,
  validateRedsysNotification,
  generateMerchantOrder,
} from "@/lib/payments/redsys";

describe("Redsys Payment Service", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe("buildRedsysForm", () => {
    it("generates form data with correct structure", () => {
      const result = buildRedsysForm({
        amountCents: 15000, // 150.00 EUR
        merchantOrder: "000001ABC123",
        productDescription: "Reserva Baqueira",
        notifyUrl: "https://example.com/api/payments/redsys/notification",
        okUrl: "https://example.com/success",
        koUrl: "https://example.com/error",
      });

      expect(result.url).toBe("https://sis-t.redsys.es:25443/sis/realizarPago");
      expect(result.Ds_SignatureVersion).toBe("HMAC_SHA256_V1");
      expect(result.Ds_MerchantParameters).toBeTruthy();
      expect(result.Ds_Signature).toBeTruthy();
    });

    it("encodes merchant parameters as valid base64 JSON", () => {
      const result = buildRedsysForm({
        amountCents: 10000,
        merchantOrder: "123456ABCDEF",
        productDescription: "Test",
        notifyUrl: "https://example.com/notify",
        okUrl: "https://example.com/ok",
        koUrl: "https://example.com/ko",
      });

      const decoded = JSON.parse(
        Buffer.from(result.Ds_MerchantParameters, "base64").toString("utf8")
      );

      expect(decoded.DS_MERCHANT_AMOUNT).toBe("10000");
      expect(decoded.DS_MERCHANT_ORDER).toBe("123456ABCDEF");
      expect(decoded.DS_MERCHANT_CURRENCY).toBe("978");
      expect(decoded.DS_MERCHANT_TRANSACTIONTYPE).toBe("0");
      expect(decoded.DS_MERCHANT_MERCHANTCODE).toBe("999008881");
      expect(decoded.DS_MERCHANT_TERMINAL).toBe("001");
    });

    it("truncates description to 125 chars", () => {
      const longDesc = "A".repeat(200);
      const result = buildRedsysForm({
        amountCents: 100,
        merchantOrder: "000001AAAAAA",
        productDescription: longDesc,
        notifyUrl: "https://example.com/n",
        okUrl: "https://example.com/ok",
        koUrl: "https://example.com/ko",
      });

      const decoded = JSON.parse(
        Buffer.from(result.Ds_MerchantParameters, "base64").toString("utf8")
      );
      expect(decoded.DS_MERCHANT_PRODUCTDESCRIPTION.length).toBe(125);
    });

    it("includes holder name when provided", () => {
      const result = buildRedsysForm({
        amountCents: 5000,
        merchantOrder: "000001BBBBBB",
        productDescription: "Test",
        notifyUrl: "https://example.com/n",
        okUrl: "https://example.com/ok",
        koUrl: "https://example.com/ko",
        holderName: "Juan Lopez",
      });

      const decoded = JSON.parse(
        Buffer.from(result.Ds_MerchantParameters, "base64").toString("utf8")
      );
      expect(decoded.DS_MERCHANT_TITULAR).toBe("Juan Lopez");
    });
  });

  describe("validateRedsysNotification", () => {
    it("validates a self-signed notification correctly", () => {
      // Generate a form, then validate it as if Redsys echoed it back
      const form = buildRedsysForm({
        amountCents: 5000,
        merchantOrder: "000001CCCCCC",
        productDescription: "Test validation",
        notifyUrl: "https://example.com/n",
        okUrl: "https://example.com/ok",
        koUrl: "https://example.com/ko",
      });

      // The signature generated by buildRedsysForm should validate
      const result = validateRedsysNotification({
        Ds_SignatureVersion: form.Ds_SignatureVersion,
        Ds_MerchantParameters: form.Ds_MerchantParameters,
        Ds_Signature: form.Ds_Signature,
      });

      // The raw data won't have Ds_Response, so isAuthorized will be false
      // but isValid should be true since the signature matches
      expect(result.isValid).toBe(true);
      expect(result.merchantOrder).toBe("000001CCCCCC");
    });

    it("rejects invalid signatures", () => {
      const form = buildRedsysForm({
        amountCents: 1000,
        merchantOrder: "000001DDDDDD",
        productDescription: "Test",
        notifyUrl: "https://example.com/n",
        okUrl: "https://example.com/ok",
        koUrl: "https://example.com/ko",
      });

      const result = validateRedsysNotification({
        Ds_SignatureVersion: form.Ds_SignatureVersion,
        Ds_MerchantParameters: form.Ds_MerchantParameters,
        Ds_Signature: "INVALID_SIGNATURE_HERE",
      });

      expect(result.isValid).toBe(false);
      expect(result.isAuthorized).toBe(false);
    });

    it("rejects invalid base64 parameters", () => {
      const result = validateRedsysNotification({
        Ds_SignatureVersion: "HMAC_SHA256_V1",
        Ds_MerchantParameters: "not-valid-base64!!!",
        Ds_Signature: "doesntmatter",
      });

      expect(result.isValid).toBe(false);
    });

    it("detects authorized payments (response 0000-0099)", () => {
      // Build a mock notification with Ds_Response in the params
      const merchantData = {
        Ds_Amount: "5000",
        Ds_Order: "000001EEEEEE",
        Ds_Response: "0000",
        Ds_AuthorisationCode: "AUTH123",
        Ds_MerchantCode: "999008881",
        Ds_Terminal: "001",
      };

      const paramsB64 = Buffer.from(JSON.stringify(merchantData)).toString("base64");

      // We need to sign this ourselves to make it valid
      const { createCipheriv, createHmac } = require("node:crypto");
      const secretKey = "sq7HjrUOBfKmC576ILgskD5srU870gJ7";
      const decodedKey = Buffer.from(secretKey, "base64");

      const orderBuffer = Buffer.alloc(8, 0);
      Buffer.from("000001EEEEEE", "utf8").copy(orderBuffer);
      const iv = Buffer.alloc(8, 0);
      const cipher = createCipheriv("des-ede3-cbc", decodedKey, iv);
      cipher.setAutoPadding(false);
      const orderKey = Buffer.concat([cipher.update(orderBuffer), cipher.final()]);

      const signature = createHmac("sha256", orderKey).update(paramsB64).digest("base64");

      const result = validateRedsysNotification({
        Ds_SignatureVersion: "HMAC_SHA256_V1",
        Ds_MerchantParameters: paramsB64,
        Ds_Signature: signature,
      });

      expect(result.isValid).toBe(true);
      expect(result.isAuthorized).toBe(true);
      expect(result.authCode).toBe("AUTH123");
      expect(result.amount).toBe(5000);
    });
  });

  describe("generateMerchantOrder", () => {
    it("generates a 12-character string", () => {
      const order = generateMerchantOrder();
      expect(order).toHaveLength(12);
    });

    it("starts with numeric characters", () => {
      const order = generateMerchantOrder();
      // First 6 chars are from timestamp — all numeric
      expect(/^\d{6}/.test(order)).toBe(true);
    });

    it("generates unique IDs", () => {
      const ids = new Set<string>();
      for (let i = 0; i < 100; i++) {
        ids.add(generateMerchantOrder());
      }
      // With random component, should be highly unique
      expect(ids.size).toBeGreaterThan(95);
    });

    it("only contains alphanumeric characters", () => {
      for (let i = 0; i < 50; i++) {
        const order = generateMerchantOrder();
        expect(/^[A-Z0-9]+$/.test(order)).toBe(true);
      }
    });
  });
});
